name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - "3.3.3"

    steps:
      - name: Setup and Install dependencies
        run: |
          gem install bundler -v 2.5.11
          ./bin/setup
      - name: Run tests
        run: ./bin/test
